using System;using System.IO;using System.Collections;using System.Collections.Generic;using System.Diagnostics;using System.Runtime.InteropServices;using System.Web.Script.Serialization;using SolidWorks.Interop.sldworks;
public static class GripperAssemble {
 static ISldWorks sw;static IModelDoc2 d;static IAssemblyDoc ass;static string root;static Dictionary<string,IComponent2> components=new Dictionary<string,IComponent2>();static List<object> results=new List<object>();static Stopwatch timer;
 static Dictionary<string,object> D(object x){return (Dictionary<string,object>)x;}static object[] A(object x){return x as object[]??((ArrayList)x).ToArray();}static double[] V(object x){return Array.ConvertAll(A(x),Convert.ToDouble);}static Dictionary<string,object> O(params object[] p){var r=new Dictionary<string,object>();for(int i=0;i<p.Length;i+=2)r[(string)p[i]]=p[i+1];return r;}static double Dot(double[] a,double[] b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];}
 static double[] Normal(string kind,double[] p){return kind=="plane"?new[]{p[0],p[1],p[2]}:new[]{p[3],p[4],p[5]};}
 static double Score(string kind,double[] p,double[] q){var a=Normal(kind,p);var b=Normal(kind,q);if(Math.Abs(Dot(a,b))<.999999)return 1e10;if(kind=="plane")return Math.Abs((p[3]-q[3])*a[0]+(p[4]-q[4])*a[1]+(p[5]-q[5])*a[2]);if(Math.Abs(p[6]-q[6])>1e-7)return 1e10;var dif=new[]{p[0]-q[0],p[1]-q[1],p[2]-q[2]};double along=Dot(dif,a);return Math.Sqrt(Math.Max(0,Dot(dif,dif)-along*along))+(kind=="circle_edge"?Math.Abs(along):0);}
 static IComponent2 FindComponent(string source){if(components.ContainsKey(source))return components[source];int slash=source.IndexOf('/');if(slash<0)throw new Exception("Unknown instance "+source);var parent=components[source.Substring(0,slash)];string target=parent.Name2+source.Substring(slash);foreach(object o in (object[])ass.GetComponents(false)){var c=(IComponent2)o;if(c.Name2==target){components[source]=c;return c;}}throw new Exception("Nested component missing "+target);}
 static IEntity Match(Dictionary<string,object> item,out int flip){var c=FindComponent((string)item["component"]);var part=(IModelDoc2)c.GetModelDoc2();if(part==null)throw new Exception("Unloaded "+c.Name2);var g=D(item["geometry"]);string kind=(string)g["kind"];var p=V(g["params"]);double best=1e10;IEntity chosen=null;double[] chosenParams=null;foreach(object bo in (object[])((IPartDoc)part).GetBodies2(0,false)){var body=(IBody2)bo;if(kind=="circle_edge"){foreach(object eo in (object[])body.GetEdges()){var ed=(IEdge)eo;var curve=(ICurve)ed.GetCurve();if(!curve.IsCircle())continue;var q=(double[])curve.CircleParams;double score=Score(kind,p,q);if(score<best){best=score;chosen=(IEntity)ed;chosenParams=q;}}}else{foreach(object fo in (object[])body.GetFaces()){var f=(IFace2)fo;var s=(ISurface)f.GetSurface();if(kind=="plane"&&!s.IsPlane()||kind=="cylinder"&&!s.IsCylinder())continue;var q=(double[])(kind=="plane"?s.PlaneParams:s.CylinderParams);double score=Score(kind,p,q);if(score>1e-6)continue;var bb=(double[])f.GetBox();var want=V(g["box"]);for(int j=0;j<6;j++)score+=Math.Abs(bb[j]-want[j])*.001;if(score<best){best=score;chosen=(IEntity)f;chosenParams=q;}}}}
 if(chosen==null||best>1e-5)throw new Exception("No matching "+kind+" on "+c.Name2+" score="+best);flip=Dot(Normal(kind,p),Normal(kind,chosenParams))<0?1:0;
 // Plane mate alignment uses the outward FACE normal, not the underlying surface parameterization.
 // The rebuilt solids are geometrically equivalent: corresponding boundary faces retain outward orientation.
 if(kind=="plane")flip=0;
 return (IEntity)c.GetCorrespondingEntity(chosen);}
 static void View(){d.ClearSelection2(true);d.ShowNamedView2("",7);d.ViewZoomtofit2();d.GraphicsRedraw2();}
 public static void Run(string folder){root=folder;timer=Stopwatch.StartNew();sw=(ISldWorks)Marshal.GetActiveObject("SldWorks.Application");string output=Path.Combine(root,"models","FullGripper.SLDASM");if(File.Exists(output))throw new Exception("Assembly exists");var ser=new JavaScriptSerializer();ser.MaxJsonLength=int.MaxValue;var data=D(ser.DeserializeObject(File.ReadAllText(Path.Combine(root,"inputs","assembly_original.json"))));var mateRows=A(ser.DeserializeObject(File.ReadAllText(Path.Combine(root,"inputs","mate_specifications.json"))));d=(IModelDoc2)sw.NewDocument(System.Environment.GetEnvironmentVariable("SW_ASSEMBLY_TEMPLATE"),0,0,0);ass=(IAssemblyDoc)d;d.SetUserPreferenceToggle(5,false);d.SetUserPreferenceToggle(6,false);d.SetUserPreferenceToggle(196,false);
 try{int index=0;foreach(object co in A(data["components"])){var info=D(co);if((string)info["parent"]!="$root")continue;string instance=(string)info["instance"];string old=(string)info["path"];string fn=Path.GetFileName(old);bool custom=fn.StartsWith("14AK-");string path=Path.Combine(root,custom?"models":"vendor",custom?"P"+fn.Substring(5):fn);int e=0,w=0;var doc=(IModelDoc2)sw.GetOpenDocumentByName(path);if(doc==null)doc=(IModelDoc2)sw.OpenDoc6(path,path.EndsWith(".SLDASM",StringComparison.OrdinalIgnoreCase)?2:1,1,"",ref e,ref w);if(doc==null)throw new Exception("Cannot load "+path+" "+e);sw.ActivateDoc3(d.GetTitle(),false,0,ref e);var c=(IComponent2)ass.AddComponent5(path,0,"",false,"",0,0,0);if(c==null)throw new Exception("AddComponent "+instance);d.ClearSelection2(true);c.Select4(false,null,false);ass.UnfixComponent();var t=V(info["transform2_raw"]);bool anchor=instance=="14AK-046-1";if(!anchor){t[9]+=.018*(1+index%3);t[10]+=.016*(1+index/3);t[11]+=.035;}c.Transform2=(MathTransform)((IMathUtility)sw.GetMathUtility()).CreateTransform(t);if(anchor){d.ClearSelection2(true);c.Select4(false,null,false);ass.FixComponent();}components[instance]=c;index++;View();Console.WriteLine("INSERT "+instance);}
 var names=new Dictionary<string,string>();foreach(object co in A(data["components"])){string sn=(string)D(co)["instance"];names[sn]=FindComponent(sn).Name2;}File.WriteAllText(Path.Combine(root,"checks","component_name_map.json"),ser.Serialize(names));
 int n=0;foreach(object mo in mateRows){var m=D(mo);int number=++n;string source=(string)m["name"];try{var ents=A(m["entities"]);int f1,f2;var e1=Match(D(ents[0]),out f1);var e2=Match(D(ents[1]),out f2);int align=Convert.ToInt32(m["alignment"]);if((f1^f2)!=0)align=align==0?1:0;d.ClearSelection2(true);var sd=(ISelectData)((ISelectionMgr)d.SelectionManager).CreateSelectData();sd.Mark=1;if(!e1.Select4(false,(SelectData)sd)||!e2.Select4(true,(SelectData)sd))throw new Exception("Selection failure");int error=0;var mate=ass.AddMate5(Convert.ToInt32(m["type"]),align,false,Convert.ToDouble(m["distance"]),0,0,0,0,0,0,0,false,false,0,out error);bool ok=mate!=null&&error==1;results.Add(O("number",number,"source_name",source,"type",m["type"],"success",ok,"api_status",error,"orientation_flips",f1+f2,"elapsed_seconds",timer.Elapsed.TotalSeconds));Console.WriteLine("MATE "+number+"/43 "+source+" status="+error);View();}catch(Exception ex){results.Add(O("number",number,"source_name",source,"type",m["type"],"success",false,"error",ex.Message,"elapsed_seconds",timer.Elapsed.TotalSeconds));Console.WriteLine("MATE FAILED "+number+" "+ex.Message);}}
 d.ForceRebuild3(false);View();int se=0,swarn=0;if(!d.Extension.SaveAs(output,0,1,null,ref se,ref swarn)||se!=0)throw new Exception("Assembly save "+se);d.SaveBMP(Path.Combine(root,"checks","full_assembly_preview.bmp"),1400,1000);Console.WriteLine("Saved FullGripper");
 }finally{File.WriteAllText(Path.Combine(root,"checks","mate_attempts.json"),ser.Serialize(results));}}
 public static void Relink(string folder){root=folder;sw=(ISldWorks)Marshal.GetActiveObject("SldWorks.Application");var ser=new JavaScriptSerializer();ser.MaxJsonLength=int.MaxValue;var data=D(ser.DeserializeObject(File.ReadAllText(Path.Combine(root,"inputs","assembly_original.json"))));var files=new HashSet<string>();foreach(object o in A(data["components"])){string p=(string)D(o)["path"];if(!Path.GetFileName(p).StartsWith("14AK-"))files.Add(p);}foreach(string old in files){string dest=Path.Combine(root,"vendor",Path.GetFileName(old));if(!File.Exists(dest))File.Copy(old,dest);}foreach(string old in files)if(old.EndsWith(".SLDASM",StringComparison.OrdinalIgnoreCase)){string dest=Path.Combine(root,"vendor",Path.GetFileName(old));foreach(string reference in files)if(reference!=old){bool changed=sw.ReplaceReferencedDocument(dest,reference,Path.Combine(root,"vendor",Path.GetFileName(reference)));if(changed)Console.WriteLine("Relinked "+Path.GetFileName(dest)+" => "+Path.GetFileName(reference));}}}
}
