using System;using System.IO;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Web.Script.Serialization;using SolidWorks.Interop.sldworks;
public static class GripperAssemblyCheck {
 static ISldWorks sw;static JavaScriptSerializer ser=new JavaScriptSerializer();
 static Dictionary<string,object> D(object x){return (Dictionary<string,object>)x;}static Dictionary<string,object> O(params object[] p){var r=new Dictionary<string,object>();for(int i=0;i<p.Length;i+=2)r[(string)p[i]]=p[i+1];return r;}
 static void Walk(IFeature f,bool sub,HashSet<string> seen,List<object> rows){while(f!=null){if(seen.Add(f.Name)){var m=f.GetSpecificFeature2() as IMate2;if(m!=null)rows.Add(O("name",f.Name,"type",m.Type,"error",f.GetErrorCode(),"suppressed",f.IsSuppressed()));else if(f.GetErrorCode()!=0)Console.WriteLine("FEATURE ERROR "+f.Name+" "+f.GetErrorCode());if(f.GetTypeName2()=="MateGroup")Walk((IFeature)f.GetFirstSubFeature(),true,seen,rows);}f=(IFeature)(sub?f.GetNextSubFeature():f.GetNextFeature());}}
 static List<object> Mates(IModelDoc2 d){var r=new List<object>();Walk((IFeature)d.FirstFeature(),false,new HashSet<string>(),r);return r;}
 static List<object> Interference(IModelDoc2 d){int e=0;sw.ActivateDoc3(d.GetTitle(),false,0,ref e);d.ClearSelection2(true);var mgr=(IInterferenceDetectionMgr)((IAssemblyDoc)d).InterferenceDetectionManager;mgr.TreatCoincidenceAsInterference=false;mgr.IgnoreHiddenBodies=false;mgr.ShowIgnoredInterferences=true;mgr.TreatSubAssembliesAsComponents=false;var rows=new List<object>();try{var hits=mgr.GetInterferences() as object[];if(hits!=null)foreach(IInterference h in hits){var names=new List<string>();foreach(IComponent2 c in (object[])h.Components)names.Add(c.Name2);rows.Add(O("components",names,"volume_mm3",h.Volume*1e9,"possible",h.IsPossibleInterference));}}finally{mgr.Done();}return rows;}
 public static void Run(string root,string mode){sw=(ISldWorks)Marshal.GetActiveObject("SldWorks.Application");ser.MaxJsonLength=int.MaxValue;var data=D(ser.DeserializeObject(File.ReadAllText(Path.Combine(root,"inputs","assembly_original.json"))));string path=mode=="source"?(string)data["source"]:Path.Combine(root,"models","FullGripper.SLDASM");int e=0,w=0;var doc=(IModelDoc2)sw.GetOpenDocumentByName(path);if(doc!=null&&mode!="source"){sw.CloseDoc(doc.GetTitle());doc=null;}if(doc==null)doc=(IModelDoc2)sw.OpenDoc6(path,2,mode=="source"?3:1,"",ref e,ref w);if(doc==null)throw new Exception("Open "+e);sw.ActivateDoc3(doc.GetTitle(),false,0,ref e);doc.ForceRebuild3(false);var ass=(IAssemblyDoc)doc;ass.ResolveAllLightWeightComponents(false);var comps=(object[])ass.GetComponents(false);var lookup=new Dictionary<string,IComponent2>();foreach(IComponent2 c in comps)lookup[c.Name2]=c;Dictionary<string,object> map=mode=="source"?null:D(ser.DeserializeObject(File.ReadAllText(Path.Combine(root,"checks","component_name_map.json"))));var poses=new List<object>();var internalMates=new List<object>();int leaves=0,sub=0,roots=0;foreach(Dictionary<string,object> info in (object[])data["components"]){string original=(string)info["instance"],name=map==null?original:(string)map[original];if(!lookup.ContainsKey(name)){poses.Add(O("source",original,"missing",true));continue;}var c=lookup[name];var md=(IModelDoc2)c.GetModelDoc2();bool isAss=md.GetType()==2;if(isAss){sub++;internalMates.Add(O("component",name,"mates",Mates(md)));}else leaves++;bool top=(string)info["parent"]=="$root";if(top)roots++;var mat=(double[])c.Transform2.ArrayData;var reference=Array.ConvertAll((object[])info["transform2_raw"],Convert.ToDouble);double delta=0,rot=0;for(int j=0;j<3;j++)delta+=Math.Pow(mat[9+j]-reference[9+j],2);for(int j=0;j<9;j++)rot=Math.Max(rot,Math.Abs(mat[j]-reference[j]));poses.Add(O("source",original,"instance",name,"path",c.GetPathName(),"top_level",top,"is_assembly",isAss,"fixed",c.IsFixed(),"constraint_status",c.GetConstrainedStatus(),"translation_error_mm",Math.Sqrt(delta)*1000,"rotation_matrix_error",rot,"transform",mat,"portable",Path.GetFullPath(c.GetPathName()).StartsWith(Path.GetFullPath(root)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)));}
 var mates=Mates(doc);var hits=Interference(doc);var report=O("mode",mode,"reopened",mode!="source","open_errors",e,"open_warnings",w,"components",poses,"api_component_count",comps.Length,"leaf_count",leaves,"subassembly_count",sub,"top_level_count",roots,"top_level_mates",mates,"internal_mates",internalMates,"interferences",hits);File.WriteAllText(Path.Combine(root,"checks",mode+"_assembly_validation.json"),ser.Serialize(report));doc.ClearSelection2(true);doc.ShowNamedView2("",7);doc.ViewZoomtofit2();doc.GraphicsRedraw2();doc.SaveBMP(Path.Combine(root,"checks",mode+"_checked_preview.bmp"),1400,1000);Console.WriteLine("CHECK "+mode+" components="+comps.Length+" mates="+mates.Count+" interferences="+hits.Count);}
}
