using System;using System.IO;using System.Collections;using System.Collections.Generic;using System.Diagnostics;using System.Runtime.InteropServices;using System.Web.Script.Serialization;using SolidWorks.Interop.sldworks;
public static class GripperBuild {
 static ISldWorks sw;static IModelDoc2 d;static IFeature[] planes;static string root,id;static Stopwatch timer;static List<string> stages=new List<string>();
 static Dictionary<string,object> D(object x){return (Dictionary<string,object>)x;}static object[] A(object x){return x as object[]??((ArrayList)x).ToArray();}static double N(object x){return Convert.ToDouble(x);}static double[] V(object x){return Array.ConvertAll(A(x),N);}
 static double[] P(double[] a){var p=(IMathPoint)((IMathUtility)sw.GetMathUtility()).CreatePoint(Array.ConvertAll(a,x=>x/1000));return (double[])((IMathPoint)p.MultiplyTransform(d.SketchManager.ActiveSketch.ModelToSketchTransform)).ArrayData;}
 static double[] XYZ(int axis,double a,double b,double n){return axis==2?new[]{a,b,n}:axis==0?new[]{n,a,b}:new[]{a,n,b};}
 static void Start(IFeature plane){d.ClearSelection2(true);if(!plane.Select2(false,0))throw new Exception("Select plane");d.SketchManager.InsertSketch(true);d.SketchManager.AddToDB=true;}
 static ISketchSegment Line(double[] a,double[] b){return d.SketchManager.CreateLine(a[0],a[1],a[2],b[0],b[1],b[2]);}
 static IFeature End(string name){d.SketchManager.AddToDB=false;var sk=d.SketchManager.ActiveSketch;d.SketchManager.FullyDefineSketch(true,true,518,true,0,null,0,null,0,0);d.SketchManager.InsertSketch(true);var f=(IFeature)d.Extension.GetLastFeatureAdded();f.Name=name;return f;}
 static IFeature PlaneFor(int axis){return axis==2?planes[0]:axis==1?planes[1]:planes[2];}
 static void Step(IFeature f,string name){if(f==null)throw new Exception("Feature failed "+name);f.Name=name;if(f.GetErrorCode()!=0)throw new Exception("Feature error "+name);d.ClearSelection2(true);d.ShowNamedView2("",7);d.ViewZoomtofit2();d.GraphicsRedraw2();Console.WriteLine(id+" | "+name);stages.Add(timer.Elapsed.TotalSeconds.ToString("F3")+"\t"+id+"\t"+name);}
 static void Cut(string name,double depth){Step(d.FeatureManager.FeatureCut3(true,false,true,depth==0?1:0,0,depth==0?.5:depth/1000,.5,false,false,false,false,0,0,false,false,false,false,false,true,true,false,false,false,0,0,false),name);}
 static void Drill(Dictionary<string,object> b,int idx){var start=V(b["start"]);int axis=Convert.ToInt32(b["axis"]),sign=Convert.ToInt32(b["sign"]);double r=N(b["diameter"])/2,dep=N(b["depth"]);int normal=axis==2?0:2;double off=start[normal];IFeature plane=PlaneFor(normal);if(Math.Abs(off)>1e-9){d.ClearSelection2(true);plane.Select2(false,0);if(d.FeatureManager.InsertRefPlane(8,off/1000,0,0,0,0)==null)throw new Exception("Drill plane");plane=(IFeature)d.Extension.GetLastFeatureAdded();plane.Name="DrillPlane_"+idx;}
 Start(plane);var tip=(double[])start.Clone();tip[axis]+=sign*(dep+r/Math.Tan(59*Math.PI/180));var edge=(double[])start.Clone();edge[axis]+=sign*dep;int radial=axis==1?0:1;edge[radial]+=r;var mouth=(double[])start.Clone();mouth[radial]+=r;var a=P(start);var ptip=P(tip);var axisLine=Line(a,ptip);Line(ptip,P(edge));Line(P(edge),P(mouth));Line(P(mouth),a);var sketch=End("BlindDrillProfile_"+idx);d.ClearSelection2(true);sketch.Select2(false,0);var sd=(ISelectData)((ISelectionMgr)d.SelectionManager).CreateSelectData();sd.Mark=4;axisLine.Select4(true,(SelectData)sd);Step(d.FeatureManager.FeatureRevolve2(true,true,false,true,false,false,0,0,2*Math.PI,0,false,false,0,0,0,0,0,true,true,true),"BlindDrill_D"+(r*2)+"_Depth"+dep+"_"+idx);}
 public static void Run(string folder){root=folder;timer=Stopwatch.StartNew();sw=(ISldWorks)Marshal.GetActiveObject("SldWorks.Application");bool old=sw.GetUserPreferenceToggle(10);sw.SetUserPreferenceToggle(10,false);try{
 var ser=new JavaScriptSerializer();var specs=ser.DeserializeObject(File.ReadAllText(Path.Combine(root,"inputs","part_specifications.json")));foreach(object op in A(specs)){var p=D(op);id=(string)p["id"];string file=Path.Combine(root,"models","P"+id+".SLDPRT");if(File.Exists(file)){Console.WriteLine("SKIP existing "+id);continue;}
 d=(IModelDoc2)sw.NewDocument(System.Environment.GetEnvironmentVariable("SW_PART_TEMPLATE"),0,0,0);var ps=new List<IFeature>();for(var f=(IFeature)d.FirstFeature();f!=null;f=(IFeature)f.GetNextFeature())if(f.GetTypeName2()=="RefPlane")ps.Add(f);planes=ps.ToArray();d.SetUserPreferenceToggle(5,false);d.SetUserPreferenceToggle(6,false);d.SetUserPreferenceToggle(196,false);int normal=Convert.ToInt32(p["profile_axis"]);double thickness=N(p["thickness"]);Start(PlaneFor(normal));var poly=A(p["polygon"]);for(int i=0;i<poly.Length;i++){var a=V(poly[i]);var b=V(poly[(i+1)%poly.Length]);Line(P(XYZ(normal,a[0],a[1],0)),P(XYZ(normal,b[0],b[1],0)));}End("FinalOutline_FromDrawing");Step(d.FeatureManager.FeatureExtrusion2(true,false,false,0,0,thickness/1000,0,false,false,false,false,0,0,false,false,false,false,true,true,true,0,0,false),"Extrude_Thickness"+thickness);
 int gi=0;foreach(object og in A(p["holes"])){var g=D(og);int ax=Convert.ToInt32(g["axis"]);Start(PlaneFor(ax));foreach(object oc in A(g["centers"])){var v=V(oc);var q=P(XYZ(ax,v[0],v[1],0));d.SketchManager.CreateCircleByRadius(q[0],q[1],q[2],N(g["diameter"])/2000);}End("HoleGroup_"+(++gi));Cut("Bores_D"+N(g["diameter"])+"_Group"+gi,N(g["depth"]));}
 int si=0;foreach(object os in A(p["slots"])){var sl=D(os);var a=V(sl["a"]);var b=V(sl["b"]);double r=N(sl["radius"]),len=Math.Sqrt(Math.Pow(b[0]-a[0],2)+Math.Pow(b[1]-a[1],2)),ux=(b[0]-a[0])/len,uy=(b[1]-a[1])/len,nx=-uy,ny=ux;Start(PlaneFor(normal));var a1=P(XYZ(normal,a[0]+nx*r,a[1]+ny*r,0));var a2=P(XYZ(normal,a[0]-nx*r,a[1]-ny*r,0));var b1=P(XYZ(normal,b[0]+nx*r,b[1]+ny*r,0));var b2=P(XYZ(normal,b[0]-nx*r,b[1]-ny*r,0));var bm=P(XYZ(normal,b[0]+ux*r,b[1]+uy*r,0));var am=P(XYZ(normal,a[0]-ux*r,a[1]-uy*r,0));Line(a1,b1);d.SketchManager.Create3PointArc(b1[0],b1[1],b1[2],b2[0],b2[1],b2[2],bm[0],bm[1],bm[2]);Line(b2,a2);d.SketchManager.Create3PointArc(a2[0],a2[1],a2[2],a1[0],a1[1],a1[2],am[0],am[1],am[2]);End("SlotProfile_"+(++si));Cut("ThroughSlot_"+si,0);}
 foreach(object on in A(p["notches"])){var n=D(on);var c=V(n["center"]);Start(PlaneFor(normal));var q=P(XYZ(normal,c[0],c[1],0));d.SketchManager.CreateCircleByRadius(q[0],q[1],q[2],N(n["radius"])/1000);End("NotchProfile");Cut("EdgeNotch_R"+N(n["radius"]),0);}
 int bi=0;foreach(object ob in A(p["blind"]))Drill(D(ob),++bi);
 d.ClearSelection2(true);d.ForceRebuild3(false);int e=0,w=0;if(!d.Extension.SaveAs(file,0,1,null,ref e,ref w)||e!=0)throw new Exception("Save "+id+" "+e);Console.WriteLine("SAVED "+id);sw.CloseDoc(d.GetTitle());}
 }finally{sw.SetUserPreferenceToggle(10,old);File.WriteAllLines(Path.Combine(root,"recordings","modeling_events.tsv"),stages);}}
}
