using System;using System.IO;using System.Text;using System.Collections.Generic;using System.Runtime.InteropServices;using SolidWorks.Interop.sldworks;
public static class GripperPrepare {
 static ISldWorks sw;static IModelDoc2 d;static StringBuilder log;static HashSet<string> seen;
 static string V(object o){var a=o as double[];return a==null?"null":string.Join(",",Array.ConvertAll(a,x=>x.ToString("G12",System.Globalization.CultureInfo.InvariantCulture)));}
 static double[] Point(ISketchPoint p,IMathTransform t){var q=(IMathPoint)((IMathUtility)sw.GetMathUtility()).CreatePoint(new[]{p.X,p.Y,p.Z});return (double[])((IMathPoint)q.MultiplyTransform(t)).ArrayData;}
 static void Walk(IFeature f,bool sub){while(f!=null){if(seen.Add(f.Name)){log.AppendLine("FEATURE "+f.Name+" | "+f.GetTypeName2()+" suppressed="+f.IsSuppressed());var dim=(IDisplayDimension)f.GetFirstDisplayDimension();while(dim!=null){var p=(IDimension)dim.GetDimension2(0);log.AppendLine("DIM "+p.FullName+"="+p.SystemValue);dim=(IDisplayDimension)f.GetNextDisplayDimension(dim);}var sk=f.GetSpecificFeature2() as ISketch;if(sk!=null){var inv=(IMathTransform)sk.ModelToSketchTransform.Inverse();foreach(object o in sk.GetSketchSegments() as object[]??new object[0]){var ln=o as ISketchLine;var a=o as ISketchArc;if(ln!=null)log.AppendLine("LINE "+V(Point((ISketchPoint)ln.GetStartPoint2(),inv))+" > "+V(Point((ISketchPoint)ln.GetEndPoint2(),inv)));if(a!=null)log.AppendLine("ARC center="+V(Point((ISketchPoint)a.GetCenterPoint2(),inv))+" r="+a.GetRadius()+" start="+V(Point((ISketchPoint)a.GetStartPoint2(),inv))+" end="+V(Point((ISketchPoint)a.GetEndPoint2(),inv)));}}Walk((IFeature)f.GetFirstSubFeature(),true);}f=(IFeature)(sub?f.GetNextSubFeature():f.GetNextFeature());}}
 public static void Inspect(string path,string output,string id){sw=(ISldWorks)Marshal.GetActiveObject("SldWorks.Application");int e=0,w=0;bool wasOpen=sw.GetOpenDocumentByName(path)!=null;d=(IModelDoc2)sw.OpenDoc6(path,1,3,"",ref e,ref w);if(d==null)throw new Exception("Open failed "+id+" "+e);log=new StringBuilder();seen=new HashSet<string>();log.AppendLine("PART "+id+"; coordinates SI metres");log.AppendLine("Volume mm3="+((IMassProperty)d.Extension.CreateMassProperty()).Volume*1e9);foreach(object o in (object[])((IPartDoc)d).GetBodies2(0,false)){var b=(IBody2)o;log.AppendLine("BODY box="+V(b.GetBodyBox()));foreach(object fo in (object[])b.GetFaces()){var f=(IFace2)fo;var s=(ISurface)f.GetSurface();if(s.IsCylinder())log.AppendLine("CYL "+V(s.CylinderParams)+" box="+V(f.GetBox()));if(s.IsCone())log.AppendLine("CONE "+V(s.ConeParams)+" box="+V(f.GetBox()));}}
 Walk((IFeature)d.FirstFeature(),false);File.WriteAllText(Path.Combine(output,id+"_source_geometry.txt"),log.ToString(),Encoding.UTF8);sw.ActivateDoc3(d.GetTitle(),false,0,ref e);d.ShowNamedView2("",7);d.ViewZoomtofit2();d.SaveBMP(Path.Combine(output,id+"_source.bmp"),1000,850);Console.WriteLine("Inspected "+id);if(!wasOpen)sw.CloseDoc(d.GetTitle());}
 static Dictionary<string,object> Obj(params object[] x){var a=new Dictionary<string,object>();for(int i=0;i<x.Length;i+=2)a[(string)x[i]]=x[i+1];return a;}
 static object Desc(object entity){var f=entity as IFace2;if(f!=null){var s=(ISurface)f.GetSurface();string kind=s.IsPlane()?"plane":s.IsCylinder()?"cylinder":s.IsCone()?"cone":"other";return Obj("kind",kind,"params",s.IsPlane()?s.PlaneParams:s.IsCylinder()?s.CylinderParams:s.IsCone()?s.ConeParams:null,"box",f.GetBox(),"area",f.GetArea());}var ed=entity as IEdge;if(ed!=null){var c=(ICurve)ed.GetCurve();return Obj("kind",c.IsCircle()?"circle_edge":c.IsLine()?"line_edge":"other_edge","params",c.IsCircle()?c.CircleParams:c.IsLine()?c.LineParams:null,"start",ed.GetStartVertex()==null?null:((IVertex)ed.GetStartVertex()).GetPoint(),"end",ed.GetEndVertex()==null?null:((IVertex)ed.GetEndVertex()).GetPoint());}return Obj("kind","unsupported","type",entity==null?"null":entity.GetType().Name);}
 public static object Mates(string path,string output){sw=(ISldWorks)Marshal.GetActiveObject("SldWorks.Application");int e=0,w=0;bool wasOpen=sw.GetOpenDocumentByName(path)!=null;d=(IModelDoc2)sw.OpenDoc6(path,2,3,"",ref e,ref w);if(d==null)throw new Exception("Source assembly open failed "+e);var rows=new List<object>();var feat=(IFeature)d.FirstFeature();while(feat!=null){if(feat.GetTypeName2()=="MateGroup"){var f=(IFeature)feat.GetFirstSubFeature();while(f!=null){var m=f.GetSpecificFeature2() as IMate2;if(m!=null){var refs=new List<object>();for(int i=0;i<m.GetMateEntityCount();i++){var me=(IMateEntity2)m.MateEntity(i);var c=(IComponent2)me.ReferenceComponent;refs.Add(Obj("component",c==null?null:c.Name2,"part_path",c==null?null:c.GetPathName(),"reference_type",me.ReferenceType2,"parameters",me.EntityParams,"geometry",Desc(me.Reference)));}var dd=m.DisplayDimension as IDisplayDimension;rows.Add(Obj("name",f.Name,"type",m.Type,"alignment",m.Alignment,"suppressed",f.IsSuppressed(),"source_error",f.GetErrorCode(),"distance",dd==null?0:((IDimension)dd.GetDimension2(0)).SystemValue,"entities",refs));}f=(IFeature)f.GetNextSubFeature();}}feat=(IFeature)feat.GetNextFeature();}sw.ActivateDoc3(d.GetTitle(),false,0,ref e);d.ShowNamedView2("",7);d.ViewZoomtofit2();d.SaveBMP(Path.Combine(output,"assembly_source.bmp"),1400,1100);Console.WriteLine("Prepared "+rows.Count+" root mate descriptions");if(!wasOpen)sw.CloseDoc(d.GetTitle());return rows;}
 public static object Outline(string path,int axis){sw=(ISldWorks)Marshal.GetActiveObject("SldWorks.Application");int e=0,w=0;d=(IModelDoc2)sw.OpenDoc6(path,1,3,"",ref e,ref w);if(d==null)throw new Exception("Open outline");IFace2 best=null;double area=0;foreach(object bo in (object[])((IPartDoc)d).GetBodies2(0,false))foreach(object fo in (object[])((IBody2)bo).GetFaces()){var f=(IFace2)fo;var b=(double[])f.GetBox();if(((ISurface)f.GetSurface()).IsPlane()&&Math.Abs(b[axis])<1e-7&&Math.Abs(b[axis+3])<1e-7&&f.GetArea()>area){best=f;area=f.GetArea();}}if(best==null)throw new Exception("No outline face");var edges=new List<object>();foreach(object lo in (object[])best.GetLoops()){var lp=(ILoop2)lo;if(lp.IsOuter())foreach(object eo in (object[])lp.GetEdges()){var ed=(IEdge)eo;edges.Add(Desc(ed));}}sw.CloseDoc(d.GetTitle());return edges;}
}
