using System;using System.IO;using System.Linq;using System.Collections.Generic;using System.Runtime.InteropServices;using System.Web.Script.Serialization;using System.Security.Cryptography;using SolidWorks.Interop.sldworks;
public static class NativeDimensionLayout {
 static JavaScriptSerializer js=new JavaScriptSerializer(){MaxJsonLength=30000000};static ISldWorks sw;static IModelDoc2 doc;static IDrawingDoc dr;static IMathUtility math;
 static object[] A(object o){return o as object[]??new object[0];}static Dictionary<string,object> M(object o){return (Dictionary<string,object>)o;}static double[] V(object o){return A(o).Select(Convert.ToDouble).ToArray();}static double N(Dictionary<string,object> o,string k){return Convert.ToDouble(o[k]);}static string S(Dictionary<string,object> o,string k){return Convert.ToString(o[k]);}
 static string Hash(string p){using(var h=SHA256.Create())using(var f=new FileStream(p,FileMode.Open,FileAccess.Read,FileShare.ReadWrite))return BitConverter.ToString(h.ComputeHash(f)).Replace("-","").ToLowerInvariant();}
 static void Need(bool b,string s){if(!b)throw new Exception(s);}static void Font(IAnnotation a,double mm){var f=(ITextFormat)a.GetTextFormat(0);f.TypeFaceName="Microsoft YaHei";f.CharHeight=mm/1000;a.SetTextFormat(0,false,f);}
 static double[] Project(IView v,double[] p){return (double[])((IMathPoint)((IMathPoint)math.CreatePoint(p)).MultiplyTransform(v.ModelToViewTransform)).ArrayData;}
 class Edge {public IEdge entity;public double[] circle,a,b;public double length;}
 static List<Edge> Cache(IView v){var rows=new List<Edge>();foreach(var co in A(v.GetVisibleComponents()))foreach(var eo in A(v.GetVisibleEntities2((Component2)co,1))){var e=eo as IEdge;if(e==null)continue;var c=(ICurve)e.GetCurve();if(c.IsCircle())rows.Add(new Edge{entity=e,circle=(double[])c.CircleParams});else if(c.IsLine()){var a=e.GetStartVertex() as IVertex;var b=e.GetEndVertex() as IVertex;if(a==null||b==null)continue;var p=(double[])a.GetPoint();var q=(double[])b.GetPoint();var x=Project(v,p);var y=Project(v,q);rows.Add(new Edge{entity=e,a=p,b=q,length=Math.Sqrt(Math.Pow(x[0]-y[0],2)+Math.Pow(x[1]-y[1],2))});}}return rows;}
 static Edge Pick(Dictionary<string,object> p,List<Edge> cache,Dictionary<int,Dictionary<string,object>> facts){if(S(p,"kind")=="datum_edge"){int axis=Convert.ToInt32(p["axis"]);double value=N(p,"value_mm")/1000;var q=cache.Where(e=>e.a!=null&&Math.Abs(e.a[axis]-value)<1e-7&&Math.Abs(e.b[axis]-value)<1e-7&&e.length>1e-5).OrderByDescending(e=>e.length).FirstOrDefault();Need(q!=null,"No visible datum edge axis="+axis+" coordinate="+value*1000);return q;}var f=facts[Convert.ToInt32(p["edge_id"])];if(S(p,"kind")=="line"||S(p,"kind")=="edge"){var a=V(f["start_si"]);var b=V(f["end_si"]);Func<double[],double[],bool> same=(x,y)=>x.Zip(y,(u,t)=>Math.Abs(u-t)).Max()<1e-7;var lines=cache.Where(x=>x.a!=null&&((same(a,x.a)&&same(b,x.b))||(same(a,x.b)&&same(b,x.a)))).ToArray();Need(lines.Length==1,"Line correspondence count="+lines.Length+" edge="+p["edge_id"]);return lines[0];}var cp=V(f["parameters_si"]);var matches=cache.Where(e=>e.circle!=null&&new[]{0,1,2,6}.All(i=>Math.Abs(cp[i]-e.circle[i])<1e-8)&&Math.Abs(Math.Abs(cp.Skip(3).Take(3).Zip(e.circle.Skip(3).Take(3),(x,y)=>x*y).Sum())-1)<1e-7).ToArray();Need(matches.Length==1,"Circle correspondence count="+matches.Length+" edge="+p["edge_id"]);return matches[0];}
 static void Select(IView view,Edge e,bool append){var sd=(ISelectData)((ISelectionMgr)doc.SelectionManager).CreateSelectData();sd.View=(View)view;Need(((IEntity)e.entity).Select4(append,(SelectData)sd),"Entity select failed");}
 static List<object> Inventory(){var rows=new List<object>();for(var v=(IView)dr.GetFirstView();v!=null;v=(IView)v.GetNextView()){var dims=new List<object>();int notes=0,tables=0,dangling=0;var noteTexts=new List<object>();foreach(var obj in A(v.GetAnnotations())){var a=(IAnnotation)obj;var dd=a.GetSpecificAnnotation() as IDisplayDimension;if(dd!=null){var dm=(IDimension)dd.GetDimension2(0);dims.Add(new{name=dm.FullName,value_si=dm.SystemValue,type=dd.Type2,position=a.GetPosition(),prefix=dd.GetText(1),suffix=dd.GetText(2),dangling=a.IsDangling()});}if(a.GetSpecificAnnotation() is INote){notes++;noteTexts.Add(new{text=((INote)a.GetSpecificAnnotation()).GetText(),position=a.GetPosition(),dangling=a.IsDangling()});}if(a.GetSpecificAnnotation() is ITableAnnotation)tables++;if(a.IsDangling())dangling++;}rows.Add(new{view=v.Name,dimensions=dims,notes=notes,note_texts=noteTexts,tables=tables,dangling=dangling});}return rows;}
 public static void Run(string planPath){var p=M(js.DeserializeObject(File.ReadAllText(planPath)));string input=S(p,"input"),output=S(p,"output"),source=S(p,"source"),report=S(p,"report");Need(!File.Exists(output),"Existing target refused");string ih=Hash(input),sh=Hash(source);var f=M(js.DeserializeObject(File.ReadAllText(S(p,"facts"))));Need(S(f,"sha256")==sh,"Changed source facts");var facts=A(f["edges"]).Select(M).ToDictionary(x=>Convert.ToInt32(x["id"]));sw=(ISldWorks)Marshal.GetActiveObject("SldWorks.Application");math=(IMathUtility)sw.GetMathUtility();int e=0,w=0;var actions=new List<object>();var errors=new List<string>();var checks=new List<object>();var expected=new Dictionary<string,double>();
 try{foreach(var opened in A(sw.GetDocuments())){var existing=(IModelDoc2)opened;string path=existing.GetPathName();Need(!String.Equals(path,input,StringComparison.OrdinalIgnoreCase),"Close input drawing before layout; preserve existing session");if(String.Equals(path,source,StringComparison.OrdinalIgnoreCase))Need(!existing.GetSaveFlag(),"Modified source is not accepted");}doc=(IModelDoc2)sw.OpenDoc6(input,3,1,"",ref e,ref w);Need(doc!=null&&e==0&&!doc.GetSaveFlag(),"Saved input required");dr=(IDrawingDoc)doc;var views=new Dictionary<string,IView>();for(var v=(IView)dr.GetFirstView();v!=null;v=(IView)v.GetNextView())views[v.Name]=v;
  foreach(var v in views.Values){string reference=v.GetReferencedModelName();if(!String.IsNullOrEmpty(reference)){Need(String.Equals(Path.GetFullPath(reference),Path.GetFullPath(source),StringComparison.OrdinalIgnoreCase),"Drawing source mismatch");Need(v.ReferencedConfiguration==S(f,"configuration"),"Drawing configuration mismatch");}}
  if(p.ContainsKey("view_moves"))foreach(var item in A(p["view_moves"])){var q=M(item);var xy=V(q["position_mm"]);if(q.ContainsKey("angle"))views[S(q,"view")].Angle=N(q,"angle");if(q.ContainsKey("scale"))views[S(q,"view")].ScaleDecimal=N(q,"scale");views[S(q,"view")].Position=new double[]{xy[0]/1000,xy[1]/1000};}
  var keeps=A(p["keep"]).Select(M).ToArray();var found=new HashSet<string>();var remove=new List<IAnnotation>();foreach(var v in views.Values)for(var dd=(IDisplayDimension)v.GetFirstDisplayDimension5();dd!=null;dd=(IDisplayDimension)dd.GetNext5()){var dm=(IDimension)dd.GetDimension2(0);var a=(IAnnotation)dd.GetAnnotation();var q=keeps.SingleOrDefault(k=>S(k,"view")==v.Name&&dm.FullName.StartsWith(S(k,"name")+"@",StringComparison.Ordinal));if(q==null){remove.Add(a);continue;}string key=S(q,"view")+"|"+S(q,"name");Need(found.Add(key),"Ambiguous keep "+key);Need(Math.Abs(dm.SystemValue-N(q,"expected_si"))<1e-8,"Model value mismatch "+key);if(q.ContainsKey("position_mm")){var xy=V(q["position_mm"]);var old=(double[])a.GetPosition();Need(a.SetPosition2(xy[0]/1000,xy[1]/1000,old[2]),"Move failed");}Font(a,3.5);if(q.ContainsKey("prefix"))dd.SetText(1,S(q,"prefix"));if(q.ContainsKey("suffix"))dd.SetText(2,S(q,"suffix"));expected[key]=dm.SystemValue;actions.Add(new{kind="retained_model_dimension",key=key,value_si=dm.SystemValue});}
  Need(found.Count==keeps.Length,"Missing planned dimension");doc.ClearSelection2(true);foreach(var a in remove)Need(a.Select3(true,null),"Delete dimension selection");if(remove.Count>0)Need(doc.Extension.DeleteSelection2(0),"Delete redundant dimensions");doc.ClearSelection2(true);
  // Delete duplicate native section captions and move explicitly authored view captions.
  foreach(var v in views.Values)foreach(var obj in A(v.GetAnnotations())){var a=(IAnnotation)obj;var note=a.GetSpecificAnnotation() as INote;if(note==null)continue;foreach(var item in A(p["note_moves"])){var move=M(item);if(move.ContainsKey("view")&&S(move,"view")!=v.Name)continue;if(note.GetText().Replace("\r","")!=S(move,"text").Replace("\r",""))continue;if(move.ContainsKey("at_mm")){var at=V(move["at_mm"]);var here=(double[])a.GetPosition();if(Math.Abs(here[0]*1000-at[0])>0.2||Math.Abs(here[1]*1000-at[1])>0.2)continue;}if(move.ContainsKey("delete")&&Convert.ToBoolean(move["delete"])){doc.ClearSelection2(true);Need(a.Select3(false,null),"Note selection");Need(doc.Extension.DeleteSelection2(0),"Delete old callout");doc.ClearSelection2(true);continue;}var xy=V(move["position_mm"]);var old=(double[])a.GetPosition();if(move.ContainsKey("at_mm")){var at=V(move["at_mm"]);if(Math.Abs(old[0]*1000-at[0])>0.2||Math.Abs(old[1]*1000-at[1])>0.2)continue;}Need(a.SetPosition2(xy[0]/1000,xy[1]/1000,old[2]),"Caption move");if(move.ContainsKey("new_text"))note.SetText(S(move,"new_text"));actions.Add(new{kind="moved_note",view=v.Name,text=note.GetText(),position=a.GetPosition()});}}
  var caches=new Dictionary<string,List<Edge>>();foreach(var q in A(p["linear"]).Concat(A(p["leaders"])).Select(M)){string name=S(q,"view");if(!caches.ContainsKey(name))caches[name]=Cache(views[name]);}
  foreach(var item in A(p["linear"])){var q=M(item);IDisplayDimension dd=null;try{var v=views[S(q,"view")];dr.ActivateView(v.Name);doc.ClearSelection2(true);Select(v,Pick(M(q["a"]),caches[v.Name],facts),false);Select(v,Pick(M(q["b"]),caches[v.Name],facts),true);var xy=V(q["position_mm"]);dd=(IDisplayDimension)(S(q,"direction")=="horizontal"?doc.AddHorizontalDimension2(xy[0]/1000,xy[1]/1000,0):doc.AddVerticalDimension2(xy[0]/1000,xy[1]/1000,0));Need(dd!=null,"Native linear creation");var dm=(IDimension)dd.GetDimension2(0);double actual=dm.SystemValue*1000;Need(Math.Abs(actual-N(q,"expected_mm"))<1e-5,"Measured "+actual+" expected "+N(q,"expected_mm"));Font((IAnnotation)dd.GetAnnotation(),3.5);if(q.ContainsKey("prefix"))dd.SetText(1,S(q,"prefix"));if(q.ContainsKey("suffix"))dd.SetText(2,S(q,"suffix"));checks.Add(new{id=S(q,"id"),view=v.Name,name=dm.FullName,actual_mm=actual,expected_mm=N(q,"expected_mm"),status="PASS"});}catch(Exception ex){if(dd!=null){doc.ClearSelection2(true);((IAnnotation)dd.GetAnnotation()).Select3(false,null);doc.Extension.DeleteSelection2(0);}errors.Add(S(q,"id")+": "+ex.Message);}doc.ClearSelection2(true);}
  foreach(var item in A(p["leaders"])){var q=M(item);try{var v=views[S(q,"view")];dr.ActivateView(v.Name);doc.ClearSelection2(true);Select(v,Pick(M(q["edge"]),caches[v.Name],facts),false);var n=(INote)doc.InsertNote(S(q,"text"));Need(n!=null,"Native leader note");var an=(IAnnotation)n.GetAnnotation();var xy=V(q["position_mm"]);Need(an.SetPosition2(xy[0]/1000,xy[1]/1000,0),"Leader move");Font(an,3.5);an.SetLeader3(1,0,true,false,false,false);Need(!an.IsDangling(),"Leader dangling");actions.Add(new{kind="attached_standard_callout",text=S(q,"text"),view=v.Name,edge_id=M(q["edge"])["edge_id"]});}catch(Exception ex){errors.Add("Leader "+S(q,"text")+": "+ex.Message);}doc.ClearSelection2(true);}
  dr.ActivateView("");Need(doc.ForceRebuild3(false),"Rebuild failed");var before=Inventory();Need(doc.Extension.SaveAs(output,0,1,null,ref e,ref w)&&e==0,"Save failed");sw.CloseDoc(doc.GetTitle());doc=(IModelDoc2)sw.OpenDoc6(output,3,1,"",ref e,ref w);Need(doc!=null&&e==0,"Reopen failed");dr=(IDrawingDoc)doc;var after=Inventory();Need(Hash(input)==ih&&Hash(source)==sh,"Source/input changed");File.WriteAllText(report,js.Serialize(new{status=errors.Count==0?"NATIVE_DIMENSIONS_REOPENED":"NATIVE_DIMENSIONS_INCOMPLETE",source_unchanged=true,input_unchanged=true,removed_dimensions=remove.Count,actions=actions,linear_checks=checks,errors=errors,before=before,after=after}),new System.Text.UTF8Encoding(false));
 }catch(Exception ex){if(!File.Exists(report))File.WriteAllText(report,js.Serialize(new{status="FAILED",error=ex.Message,actions=actions}),new System.Text.UTF8Encoding(false));throw;}finally{if(doc!=null)sw.CloseDoc(doc.GetTitle());doc=null;dr=null;sw=null;math=null;}}
}
